server:
  port: 8081
spring:
  application:
    name: chese
  redis:
    host: localhost
    port: 6379
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://120.78.94.125:3306/chese?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
      username: chese
      password: 1234
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.onlinechese.entys
  config-location: classpath:mybatis/mybatis.cfg.xml
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  reasonable: true
  params: count=countSql
#logging:
# level:
#   root: debug

